#ifndef MKTPASSWORD_GLOBAL_H
#define MKTPASSWORD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MKTPASSWORD_LIBRARY)
#  define MKTPASSWORDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MKTPASSWORDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MKTPASSWORD_GLOBAL_H